env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[0]
    TG_TOKEN: ENCRYPTED[0]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G
